services:
  zookeeper:
    image: confluentinc/cp-zookeeper:6.1.1
    container_name: zookeeper
    platform: linux/amd64
    ports:
      - "2181:2181"
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181

  kafka:
    image: confluentinc/cp-kafka:6.1.1
    container_name: kafka
    platform: linux/amd64
    depends_on:
      - zookeeper
    ports:
      - '9092:9092'
    expose:
      - '29092'
    environment:
      KAFKA_ZOOKEEPER_CONNECT: 'zookeeper:2181'
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:29092,PLAINTEXT_HOST://localhost:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: '1'
      KAFKA_MIN_INSYNC_REPLICAS: '1'
    healthcheck:
      test: ["CMD", "nc", "-z", "localhost", "9092"]
      interval: 10s
      timeout: 10s
      retries: 10

  producer:
    build:
      context: ./producer
    container_name: kafka_producer
    depends_on:
      kafka:
        condition: service_healthy
      zookeeper:
        condition: service_started
    networks:
      - default
    environment:
      KAFKA_BROKER: kafka:29092
      SOCKET_HOST: sensor_container
      SOCKET_PORT: 5555

  consumer:
    build:
      context: ./consumer
    container_name: kafka_consumer
    depends_on:
      kafka:
        condition: service_healthy
    networks:
      - default
    environment:
      KAFKA_BROKER: kafka:29092

  sensor:
    image: sensor
    container_name: sensor_container
    networks:
      - default
    ports:
      - "5555:5555"

networks:
  default:
    driver: bridge